[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.wasm-clean]
command = "cargo"
args = ["clean", "--target-dir=static/wasm"]

[tasks.wasm-build]
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "--help" }
command = "wasm-pack"
args = ["build", "--dev", "--target=no-modules", "--out-name=roguelike", "--out-dir=static/wasm/"]
dependencies = ["wasm-clean", "format"]

[tasks.wasm-release]
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "--help" }
command = "wasm-pack"
args = ["build", "--release", "--target=no-modules", "--out-name=roguelike", "--out-dir=static/wasm/"]
dependencies = ["clean", "wasm-clean", "format"]

[tasks.serve]
install_crate = { crate_name = "simple-http-server", binary = "simple-http-server", test_arg = "--help" }
command = "simple-http-server"
args = ["-i", "static/", "--ip", "127.0.0.1", "-p", "8000", "--nocache"]
dependencies = ["wasm-build"]

[tasks.run]
dependencies = ["serve"]
watch = { no_git_ignore = false, ignore_pattern = "static/wasm/" }

[tasks.release]
dependencies = ["wasm-release"]

[tasks.docker-build]
command = "docker"
args = ["buildx", "build", "--tag=daluca/roguelike-tutorial:latest", "--file=docker/Dockerfile", "."]
