[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.wasm-clean]
command = "cargo"
args = ["clean", "--target-dir=static/wasm"]

[tasks.wasm-build]
install_crate = "wasm-pack"
command = "wasm-pack"
args = ["build", "--dev", "--target=no-modules", "--out-name=roguelike", "--out-dir=static/wasm/"]
dependencies = ["wasm-clean", "format"]

[tasks.wasm-release]
install_crate = "wasm-pack"
command = "wasm-pack"
args = ["build", "--release", "--target=no-modules", "--out-name=roguelike", "--out-dir=static/wasm/"]

[tasks.serve]
install_crate = "simple-http-server"
command = "simple-http-server"
args = ["-i", "static/", "--ip", "127.0.0.1", "-p", "8000", "--nocache"]
dependencies = ["wasm-build"]

[tasks.run]
dependencies = ["serve"]
watch = { no_git_ignore = false, ignore_pattern = "static/wasm/" }

[tasks.release]
dependencies = ["wasm-release"]
