---
name: Build and Deploy

on:
  push:
    branches: [main]
    paths:
      - src/
      - resources/
      - static/
      - Cargo.toml
      - Makefile.toml
      - .github/workflows/github-pages.yml

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: install cargo-make
        uses: davidB/rust-cargo-make@v1

      - name: install wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0

      - name: install cargo-make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-make

      - name: build release
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: release

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: static
